baseURL = "https://nerdatico.com.br/"
canonifyURLs=true
pluralizeListTitles = false
summaryLength   = 25

theme           = "BlogRa"
languageCode    = "pt-br"
title           = "Nerdático"

[permalinks]
posts = "/:slug/"
sections = "/:slug/"

[sitemap]
  filename = "sitemap.xml"

disqusShortname = "xxx"

[services]
  [services.disqus]
    shortname = 'xxx'

[params]
    description     = "Nerdático é um blog de curiosidades, ciência e filosofia aplicadas à cultura pop."
    contactEmail    = "nerdatico@icloud.com"
    footer          = ""
    googleSearch    = "b6078b7db750a49ab"
    googleAnalytics = "G-DT5DYZNPED" #v4
    adsense         = "pub-3892696655399246"
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page

    # Social Media Params
    facebook   = "https://www.facebook.com/people/Nerdático/61579992813043/"
    twitter    = "https://x.com/nerdatico"
    youtube    = "https://www.youtube.com/#"
    instagram  = "https://www.instagram.com/nerdatico/"
    github     = "https://github.com/#"
    pinterest  = ""
    linkedin   = "https://www.linkedin.com/in/#/"
    


# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Colunas"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "divider"
                weight = 3
            [[menu.main]]
                parent = "blog"
                name = "Tags"
                url = "/tags/"
                weight = 4
    [[menu.main]]
        name = "Sobre"
        url = "/about/"
        weight = 3
    [[menu.main]]
        name = "Contato"
        url = "/contact/"
        weight = 4

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"  # <---- ESTA É A LINHA CHAVE
  isPlainText = false

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100

[[related.indices]]
name = "tags"
weight = 80

[[related.indices]]
name = "categories"
weight = 60